APP_NAME: Sotaca
SECRET_TOKEN: 7f7bfe337bfa5adeac8e974807f3bc13206cb0d3fe0d3787afbd52be0fdb841485e38396bf21904ca00814e535ea018f81d332be56df4fad015defc659d20f64
aws_access_key_id: AKIAJQNB77WSRJN64BIA
aws_secret_access_key: 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
aws_bucket: sotacauk
aws_host: http://sotacauk.s3.amazonaws.com

development:
    paypal_email: tmaxim_1353583741_biz@gmail.com
    paypal_secret: paypaypay
    paypal_cert_id: WHTHD9NMQC2XE
    paypal_signature: AFcWxV21C7fd0v3bYYYRCpSSRl31AuFHlWIFdTBe5D.OUM41TxF5wLLb
    paypal_url: https://www.sandbox.paypal.com/cgi-bin/webscr
    carrierwave_store: ':file'

test:
    paypal_email: test@example.com
    paypal_secret: testsecret
    paypal_cert_id: X123456789
    paypal_url: testpaypalurl
    carrierwave_store: ':file'

production:
    paypal_email: leegoo_api1.sotaca1898.com
    paypal_secret: 6P7WFUWNSJQQ7GFT
    paypal_cert_id: DG7G252GTGQ3Y
    paypal_signature: AFcWxV21C7fd0v3bYYYRCpSSRl31A3KQFwVSX7hA6hEVfEMndqCa9AYk
    paypal_url: https://www.paypal.com/cgi-bin/webscr
    carrierwave_store: ':s3'

