package_assets:         on          # (on, off, always)
embed_assets:           off          # (on, off, datauri)
compress_assets:        on          # (on, off)
gzip_assets:            on          # (on, off)


javascripts:
  workspace:
    - public/javascripts/jquery.js
    - public/javascripts/rails.js
    - public/javascripts/application.js
    - public/javascripts/product.js
    - public/javascripts/autocomplete-rails.js
    - public/javascripts/social_share_buttons.js
    - public/javascripts/nested_form.js
    - public/javascripts/tiptip.js

stylesheets:
  common:
    - public/stylesheets/application.css
    - public/stylesheets/facebox.css
