require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe AdressesController do

  # This should return the minimal set of attributes required to create a valid
  # Adress. As you add validations to Adress, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  describe "GET index" do
    it "assigns all adresses as @adresses" do
      adress = Adress.create! valid_attributes
      get :index
      assigns(:adresses).should eq([adress])
    end
  end

  describe "GET show" do
    it "assigns the requested adress as @adress" do
      adress = Adress.create! valid_attributes
      get :show, :id => adress.id.to_s
      assigns(:adress).should eq(adress)
    end
  end

  describe "GET new" do
    it "assigns a new adress as @adress" do
      get :new
      assigns(:adress).should be_a_new(Adress)
    end
  end

  describe "GET edit" do
    it "assigns the requested adress as @adress" do
      adress = Adress.create! valid_attributes
      get :edit, :id => adress.id.to_s
      assigns(:adress).should eq(adress)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Adress" do
        expect {
          post :create, :adress => valid_attributes
        }.to change(Adress, :count).by(1)
      end

      it "assigns a newly created adress as @adress" do
        post :create, :adress => valid_attributes
        assigns(:adress).should be_a(Adress)
        assigns(:adress).should be_persisted
      end

      it "redirects to the created adress" do
        post :create, :adress => valid_attributes
        response.should redirect_to(Adress.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved adress as @adress" do
        # Trigger the behavior that occurs when invalid params are submitted
        Adress.any_instance.stub(:save).and_return(false)
        post :create, :adress => {}
        assigns(:adress).should be_a_new(Adress)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Adress.any_instance.stub(:save).and_return(false)
        post :create, :adress => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested adress" do
        adress = Adress.create! valid_attributes
        # Assuming there are no other adresses in the database, this
        # specifies that the Adress created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Adress.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => adress.id, :adress => {'these' => 'params'}
      end

      it "assigns the requested adress as @adress" do
        adress = Adress.create! valid_attributes
        put :update, :id => adress.id, :adress => valid_attributes
        assigns(:adress).should eq(adress)
      end

      it "redirects to the adress" do
        adress = Adress.create! valid_attributes
        put :update, :id => adress.id, :adress => valid_attributes
        response.should redirect_to(adress)
      end
    end

    describe "with invalid params" do
      it "assigns the adress as @adress" do
        adress = Adress.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Adress.any_instance.stub(:save).and_return(false)
        put :update, :id => adress.id.to_s, :adress => {}
        assigns(:adress).should eq(adress)
      end

      it "re-renders the 'edit' template" do
        adress = Adress.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Adress.any_instance.stub(:save).and_return(false)
        put :update, :id => adress.id.to_s, :adress => {}
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested adress" do
      adress = Adress.create! valid_attributes
      expect {
        delete :destroy, :id => adress.id.to_s
      }.to change(Adress, :count).by(-1)
    end

    it "redirects to the adresses list" do
      adress = Adress.create! valid_attributes
      delete :destroy, :id => adress.id.to_s
      response.should redirect_to(adresses_url)
    end
  end

end
