require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe StartImagesController do

  # This should return the minimal set of attributes required to create a valid
  # StartImage. As you add validations to StartImage, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  describe "GET index" do
    it "assigns all start_images as @start_images" do
      start_image = StartImage.create! valid_attributes
      get :index
      assigns(:start_images).should eq([start_image])
    end
  end

  describe "GET show" do
    it "assigns the requested start_image as @start_image" do
      start_image = StartImage.create! valid_attributes
      get :show, :id => start_image.id.to_s
      assigns(:start_image).should eq(start_image)
    end
  end

  describe "GET new" do
    it "assigns a new start_image as @start_image" do
      get :new
      assigns(:start_image).should be_a_new(StartImage)
    end
  end

  describe "GET edit" do
    it "assigns the requested start_image as @start_image" do
      start_image = StartImage.create! valid_attributes
      get :edit, :id => start_image.id.to_s
      assigns(:start_image).should eq(start_image)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new StartImage" do
        expect {
          post :create, :start_image => valid_attributes
        }.to change(StartImage, :count).by(1)
      end

      it "assigns a newly created start_image as @start_image" do
        post :create, :start_image => valid_attributes
        assigns(:start_image).should be_a(StartImage)
        assigns(:start_image).should be_persisted
      end

      it "redirects to the created start_image" do
        post :create, :start_image => valid_attributes
        response.should redirect_to(StartImage.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved start_image as @start_image" do
        # Trigger the behavior that occurs when invalid params are submitted
        StartImage.any_instance.stub(:save).and_return(false)
        post :create, :start_image => {}
        assigns(:start_image).should be_a_new(StartImage)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        StartImage.any_instance.stub(:save).and_return(false)
        post :create, :start_image => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested start_image" do
        start_image = StartImage.create! valid_attributes
        # Assuming there are no other start_images in the database, this
        # specifies that the StartImage created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        StartImage.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => start_image.id, :start_image => {'these' => 'params'}
      end

      it "assigns the requested start_image as @start_image" do
        start_image = StartImage.create! valid_attributes
        put :update, :id => start_image.id, :start_image => valid_attributes
        assigns(:start_image).should eq(start_image)
      end

      it "redirects to the start_image" do
        start_image = StartImage.create! valid_attributes
        put :update, :id => start_image.id, :start_image => valid_attributes
        response.should redirect_to(start_image)
      end
    end

    describe "with invalid params" do
      it "assigns the start_image as @start_image" do
        start_image = StartImage.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        StartImage.any_instance.stub(:save).and_return(false)
        put :update, :id => start_image.id.to_s, :start_image => {}
        assigns(:start_image).should eq(start_image)
      end

      it "re-renders the 'edit' template" do
        start_image = StartImage.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        StartImage.any_instance.stub(:save).and_return(false)
        put :update, :id => start_image.id.to_s, :start_image => {}
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested start_image" do
      start_image = StartImage.create! valid_attributes
      expect {
        delete :destroy, :id => start_image.id.to_s
      }.to change(StartImage, :count).by(-1)
    end

    it "redirects to the start_images list" do
      start_image = StartImage.create! valid_attributes
      delete :destroy, :id => start_image.id.to_s
      response.should redirect_to(start_images_url)
    end
  end

end
